/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyBackgroundVideoComponent {
    'muted': boolean;
    'poster': string;
    'src': string;
  }
}

declare global {


  interface HTMLMyBackgroundVideoComponentElement extends Components.MyBackgroundVideoComponent, HTMLStencilElement {}
  var HTMLMyBackgroundVideoComponentElement: {
    prototype: HTMLMyBackgroundVideoComponentElement;
    new (): HTMLMyBackgroundVideoComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-background-video-component': HTMLMyBackgroundVideoComponentElement;
  }
}

declare namespace LocalJSX {
  interface MyBackgroundVideoComponent extends JSXBase.HTMLAttributes<HTMLMyBackgroundVideoComponentElement> {
    'muted'?: boolean;
    'poster'?: string;
    'src'?: string;
  }

  interface IntrinsicElements {
    'my-background-video-component': MyBackgroundVideoComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


